create sequence hibernate_sequence start with 1 increment by 1;

    create table j5s_bundle (
       id bigint generated by default as identity,
        environment varchar(255),
        name varchar(255),
        swid varchar(255),
        version varchar(255),
        primary key (id)
    );

    create table j5s_swid (
       id bigint not null,
        name varchar(10) not null,
        prod_installed date,
        prod_version varchar(255),
        remark varchar(255),
        te1_installed date,
        te1_version varchar(255),
        te2_installed date,
        te2_version varchar(255),
        primary key (id)
    );

    create table j5s_swid_bundles (
       runner_id bigint not null,
        bundles_id bigint not null,
        primary key (runner_id, bundles_id)
    );

    create table j5s_timesheet (
       id bigint not null,
        active boolean,
        finish timestamp,
        number integer,
        remark varchar(255),
        start timestamp,
        primary key (id)
    );

    alter table j5s_swid 
       add constraint UK_k9xb6a6ijyy630gkfie280d85 unique (name);

    alter table j5s_swid_bundles 
       add constraint FKjo3tkdt3mb281i9ljfkdlah84 
       foreign key (bundles_id) 
       references j5s_bundle;

    alter table j5s_swid_bundles 
       add constraint FKpt8k2bwyi4cg9mpjcyamgve9 
       foreign key (runner_id) 
       references j5s_swid;
